
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Aug 25 2025 15:31:29 +08 (Aug 25 2025 07:31:29 UTC)

// Verification Directory fv/top 

module top(clk_50mhz, rst_n, sw, led, HEX0, HEX1, HEX2, HEX3, HEX4,
     HEX5);
  input clk_50mhz, rst_n;
  input [3:0] sw;
  output [3:0] led;
  output [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5;
  wire clk_50mhz, rst_n;
  wire [3:0] sw;
  wire [3:0] led;
  wire [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5;
  wire n_0, slow_clk;
  gesture_display disp(.gesture_code (led), .HEX0 (HEX0), .HEX1 (HEX1),
       .HEX2 (HEX2), .HEX3 (HEX3), .HEX4 (HEX4), .HEX5 (HEX5));
  clock_divider u1(.clk_in (clk_50mhz), .rst_n (rst_n), .clk_out
       (slow_clk));
  gesture_fsm u2(.clk (slow_clk), .rst (n_0), .sensor_in (sw), .gesture
       (led));
  INVXL g43(.A (rst_n), .Y (n_0));
endmodule

